villagerfollows.can.leash.baby=0 #0=false, 1=true | default: 0
villagerfollows.can.leash.villager=1 #0=false, 1=true | default: 1
villagerfollows.can.leash.zombie.villager=0 #0=false, 1=true | default: 0
villagerfollows.can.leash.bat=0 #0=false, 1=true | default: 0
villagerfollows.can.leash.turtle=0 #0=false, 1=true | default: 0

